spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/coordination-system-dev
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    contexts: dev